changelog:
  exclude:
    labels:
      - ignore-for-release
      - question
      - documentation
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Buf fixes 🐛
        labels:
          - bug
    - title: Other Changes
      labels:
        - "*"
