import { InjectionToken } from '@angular/core';
import {
  mdiCheck,
  mdiChevronDown,
  mdiClose,
  mdiCloseCircle,
  mdiPencil,
  mdiArrowUp,
  mdiArrowDown,
  mdiPageFirst,
  mdiPageLast,
  mdiChevronLeft,
  mdiChevronRight,
} from '@mdi/js';
import type { EntireIconSettings, IconSettings } from './icon.interface';

export const DEFAULT_ICON_SETTINGS: EntireIconSettings = {
  defaultSet: 'mdi',
  svgIconSets: {
    custom: {
      mdiCheck,
      mdiChevronDown,
      mdiClose,
      mdiCloseCircle,
      mdiPencil,
      mdiArrowUp,
      mdiArrowDown,
      mdiPageFirst,
      mdiPageLast,
      mdiChevronLeft,
      mdiChevronRight,
    },
    mdiSVG: {
      mdiCheck,
      mdiChevronDown,
      mdiClose,
      mdiCloseCircle,
      mdiPencil,
      mdiArrowUp,
      mdiArrowDown,
      mdiPageFirst,
      mdiPageLast,
      mdiChevronLeft,
      mdiChevronRight,
    },
  },
  defaultSize: 'regular',
  internalIcons: {
    custom: {
      check: 'mdiCheck',
      chevronDown: 'mdiChevronDown',
      close: 'mdiClose',
      closeCircle: 'mdiCircleClose',
      edit: 'mdiPencil',
      arrowUp: 'mdiArrowUp',
      arrowDown: 'mdiArrowDown',
      pageFirst: 'mdiPageFirst',
      pageLast: 'mdiPageLast',
      chevronLeft: 'mdiChevronLeft',
      chevronRight: 'mdiChevronRight',
    },
    fa4: {
      check: 'fa-check',
      chevronDown: 'fa-chevron-down',
      close: 'fa-close',
      closeCircle: 'fa-times-circle',
      edit: 'fa-pencil',
      arrowUp: 'fa-arrow-up',
      arrowDown: 'fa-arrow-down',
      pageFirst: 'fa-step-backward',
      pageLast: 'fa-step-forward',
      chevronLeft: 'fa-chevron-left',
      chevronRight: 'fa-chevron-right',
    },
    fa5: {
      check: 'fa-check',
      chevronDown: 'fa-chevron-down',
      close: 'fa-close',
      closeCircle: 'fa-times-circle',
      edit: 'fa-pencil',
      arrowUp: 'fa-arrow-up',
      arrowDown: 'fa-arrow-down',
      pageFirst: 'fa-step-backward',
      pageLast: 'fa-step-forward',
      chevronLeft: 'fa-chevron-left',
      chevronRight: 'fa-chevron-right',
    },
    md: {
      check: 'check',
      chevronDown: 'expand_more',
      close: 'close',
      closeCircle: 'highlight_off',
      edit: 'edit',
      arrowUp: 'arrow_upward',
      arrowDown: 'arrow_downward',
      pageFirst: 'first_page',
      pageLast: 'last_page',
      chevronLeft: 'chevron_left',
      chevronRight: 'chevron_right',
    },
    mdi: {
      check: 'mdi-check',
      chevronDown: 'mdi-chevron-down',
      close: 'mdi-close',
      closeCircle: 'mdi-close-circle',
      edit: 'mdi-pencil',
      arrowUp: 'mdi-arrow-up',
      arrowDown: 'mdi-arrow-down',
      pageFirst: 'mdi-page-first',
      pageLast: 'mdi-page-last',
      chevronLeft: 'mdi-chevron-left',
      chevronRight: 'mdi-chevron-right',
    },
    mdiSVG: {
      check: 'mdiCheck',
      chevronDown: 'mdiChevronDown',
      close: 'mdiClose',
      closeCircle: 'mdiCloseCircle',
      edit: 'mdiPencil',
      arrowUp: 'mdiArrowUp',
      arrowDown: 'mdiArrowDown',
      pageFirst: 'mdiPageFirst',
      pageLast: 'mdiPageLast',
      chevronLeft: 'mdiChevronLeft',
      chevronRight: 'mdiChevronRight',
    },
    faSVG: {
      check: '',
      chevronDown: '',
      close: '',
      closeCircle: '',
      edit: '',
      arrowUp: '',
      arrowDown: '',
      pageFirst: '',
      pageLast: '',
      chevronLeft: '',
      chevronRight: '',
    },
  },
};

export const ICON_SETTINGS = new InjectionToken<IconSettings>('Icon Settings');
