import { InjectionToken } from '@angular/core';
import {
  mdiCheck,
  mdiChevronDown,
  mdiClose,
  mdiCloseCircle,
  mdiPencil,
  mdiArrowUp,
  mdiArrowDown,
  mdiArrowLeft,
  mdiArrowRight,
} from '@mdi/js';
import type { EntireIconSettings, IconSettings } from './icon.interface';

export const DEFAULT_ICON_SETTINGS: EntireIconSettings = {
  defaultSet: 'mdi',
  svgIconSets: {
    custom: {
      mdiCheck,
      mdiChevronDown,
      mdiClose,
      mdiCloseCircle,
      mdiPencil,
      mdiArrowUp,
      mdiArrowDown,
      mdiArrowLeft,
      mdiArrowRight,
    },
    mdiSVG: {
      mdiCheck,
      mdiChevronDown,
      mdiClose,
      mdiCloseCircle,
      mdiPencil,
      mdiArrowUp,
      mdiArrowDown,
      mdiArrowLeft,
      mdiArrowRight,
    },
  },
  defaultSize: 'regular',
  internalIcons: {
    custom: {
      check: 'mdiCheck',
      chevronDown: 'mdiChevronDown',
      close: 'mdiClose',
      closeCircle: 'mdiCircleClose',
      edit: 'mdiPencil',
      arrowUp: 'mdiArrowUp',
      arrowDown: 'mdiArrowDown',
      arrowLeft: 'mdiArrowLeft',
      arrowRight: 'mdiArrowRight',
    },
    fa4: {
      check: 'fa-check',
      chevronDown: 'fa-chevron-down',
      close: 'fa-close',
      closeCircle: 'fa-times-circle',
      edit: 'fa-pencil',
      arrowUp: 'fa-arrow-up',
      arrowDown: 'fa-arrow-down',
      arrowLeft: 'fa-arrow-left',
      arrowRight: 'fa-arrow-right',
    },
    fa5: {
      check: 'fa-check',
      chevronDown: 'fa-chevron-down',
      close: 'fa-close',
      closeCircle: 'fa-times-circle',
      edit: 'fa-pencil',
      arrowUp: 'fa-arrow-up',
      arrowDown: 'fa-arrow-down',
      arrowLeft: 'fa-arrow-left',
      arrowRight: 'fa-arrow-right',
    },
    md: {
      check: 'check',
      chevronDown: 'expand_more',
      close: 'close',
      closeCircle: 'highlight_off',
      edit: 'edit',
      arrowUp: 'arrow_upward',
      arrowDown: 'arrow_downward',
      arrowLeft: 'arrow_back',
      arrowRight: 'arrow_forward',
    },
    mdi: {
      check: 'mdi-check',
      chevronDown: 'mdi-chevron-down',
      close: 'mdi-close',
      closeCircle: 'mdi-close-circle',
      edit: 'mdi-pencil',
      arrowUp: 'mdi-arrow-up',
      arrowDown: 'mdi-arrow-down',
      arrowLeft: 'mdi-arrow-left',
      arrowRight: 'mdi-arrow-right',
    },
    mdiSVG: {
      check: 'mdiCheck',
      chevronDown: 'mdiChevronDown',
      close: 'mdiClose',
      closeCircle: 'mdiCloseCircle',
      edit: 'mdiPencil',
      arrowUp: 'mdiArrowUp',
      arrowDown: 'mdiArrowDown',
      arrowLeft: 'mdiArrowLeft',
      arrowRight: 'mdiArrowRight',
    },
    faSVG: {
      check: '',
      chevronDown: '',
      close: '',
      closeCircle: '',
      edit: '',
      arrowUp: '',
      arrowDown: '',
      arrowLeft: '',
      arrowRight: '',
    },
  },
};

export const ICON_SETTINGS = new InjectionToken<IconSettings>('Icon Settings');
