#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "\nChecking commit message…\n"
echo "The message must be formatted according to the Conventional Commits specification following the Angular types"
echo "https://www.conventionalcommits.org/en/v1.0.0/#summary"
echo "https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines"
echo ""
npx --no -- commitlint --edit "${1}"
