on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install node.js v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Publish
        run: |
          yarn install --immutable
          yarn build:anglify
          cp README.md dist/libs/anglify/README.md
          cd dist/libs/anglify
          yarn npm publish --access public
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
