on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
      - name: Publish
        run: |
          npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
          npm ci
          npm run build:anglify
          cd dist/anglify
          npm pack
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.TOKEN_FOR_NPM }}
